name: Check docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docgen:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Check docs
        run: |
          nvim --version
          make docgen
          git diff --exit-code
