name: Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lua_format:
    name: lua-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install --server=https://luarocks.org/dev luaformatter

      - name: Check formatting
        run: make format-check
